export interface ManufacturerColor {
  name: string;
  hex: string;
}

export interface MaterialColorSet {
  material: string;
  colors: ManufacturerColor[];
}

export interface ManufacturerCatalog {
  name: string;
  materials: MaterialColorSet[];
}

const ELEGOO: ManufacturerCatalog = {
  name: 'Elegoo',
  materials: [
    {
      material: 'PLA',
      colors: [
        { name: 'Black', hex: '#000000' },
        { name: 'White', hex: '#FFFFFF' },
        { name: 'Grey', hex: '#8F949B' },
        { name: 'Space Grey', hex: '#5D5D5D' },
        { name: 'Red', hex: '#EA140E' },
        { name: 'Orange', hex: '#FD7C18' },
        { name: 'Yellow', hex: '#F6D701' },
        { name: 'Neon Green', hex: '#08E327' },
        { name: 'Sea Green', hex: '#1ABC83' },
        { name: 'Sky Blue', hex: '#27B2D0' },
        { name: 'Dark Blue', hex: '#2240AF' },
        { name: 'Purple', hex: '#603BA0' },
        { name: 'Pink', hex: '#F9B0BD' },
        { name: 'Brown', hex: '#9E6A4B' },
        { name: 'Beige', hex: '#FEE7BF' },
        { name: 'Translucent', hex: '#E9E9E7' },
        { name: 'Wood Color', hex: '#B19870' },
        { name: 'Copper Filled', hex: '#895837' },
      ],
    },
    {
      material: 'PLA+',
      colors: [
        { name: 'Black', hex: '#000000' },
        { name: 'White', hex: '#FFFFFF' },
        { name: 'Grey', hex: '#8F949B' },
        { name: 'Space Grey', hex: '#5D5D5D' },
        { name: 'Red', hex: '#EA140E' },
        { name: 'Orange', hex: '#FD7C18' },
        { name: 'Yellow', hex: '#F6D701' },
        { name: 'Neon Green', hex: '#08E327' },
        { name: 'Sea Green', hex: '#1ABC83' },
        { name: 'Sky Blue', hex: '#27B2D0' },
        { name: 'Dark Blue', hex: '#2240AF' },
        { name: 'Purple', hex: '#603BA0' },
        { name: 'Pink', hex: '#F9B0BD' },
        { name: 'Brown', hex: '#9E6A4B' },
        { name: 'Beige', hex: '#FEE7BF' },
        { name: 'Translucent', hex: '#E9E9E7' },
        { name: 'Wood Color', hex: '#B19870' },
      ],
    },
    {
      material: 'Rapid PLA+',
      colors: [
        { name: 'Black', hex: '#000000' },
        { name: 'White', hex: '#FFFFFF' },
        { name: 'Grey', hex: '#8F949B' },
        { name: 'Silver', hex: '#C0C0C0' },
        { name: 'Red', hex: '#EA140E' },
        { name: 'Orange', hex: '#FD7C18' },
        { name: 'Yellow', hex: '#F6D701' },
        { name: 'Green', hex: '#08E327' },
        { name: 'Blue', hex: '#2240AF' },
        { name: 'Brown', hex: '#9E6A4B' },
        { name: 'Beige', hex: '#FEE7BF' },
      ],
    },
    {
      material: 'PLA Pro',
      colors: [
        { name: 'Black', hex: '#000000' },
        { name: 'White', hex: '#FFFFFF' },
        { name: 'Grey', hex: '#8F949B' },
        { name: 'Silver', hex: '#C0C0C0' },
        { name: 'True Red', hex: '#CC0000' },
        { name: 'Burgundy Red', hex: '#800020' },
        { name: 'Blue', hex: '#2240AF' },
        { name: 'Light Blue', hex: '#6CB4EE' },
        { name: 'Green', hex: '#228B22' },
        { name: 'Neon Green', hex: '#08E327' },
        { name: 'Yellow', hex: '#F6D701' },
        { name: 'Purple', hex: '#603BA0' },
        { name: 'Hot Pink', hex: '#FF69B4' },
        { name: 'Beige', hex: '#FEE7BF' },
      ],
    },
    {
      material: 'PLA Matte',
      colors: [
        { name: 'Matte Black', hex: '#1C1C1C' },
        { name: 'Matte White', hex: '#F0F0F0' },
        { name: 'Slate Grey', hex: '#708090' },
        { name: 'Ruby Red', hex: '#9B111E' },
        { name: 'Orange', hex: '#FD7C18' },
        { name: 'Sunshine Yellow', hex: '#FFDA03' },
        { name: 'Teal Green', hex: '#008080' },
        { name: 'Mint Green', hex: '#98FB98' },
        { name: 'Navy Blue', hex: '#001F5B' },
        { name: 'Ice Blue', hex: '#99CCEE' },
        { name: 'Lavender Purple', hex: '#B57EDC' },
        { name: 'Sakura Pink', hex: '#FFB7C5' },
        { name: 'Earth Brown', hex: '#7B5B3A' },
        { name: 'Beige', hex: '#E8D5B7' },
      ],
    },
    {
      material: 'PLA Silk',
      colors: [
        { name: 'Silk Gold', hex: '#E2AC00' },
        { name: 'Silk Silver Grey', hex: '#93969B' },
        { name: 'Silk Copper', hex: '#B87333' },
        { name: 'Silk White', hex: '#F5F5F0' },
        { name: 'Silk Red', hex: '#CC2233' },
        { name: 'Silk Coral Pink', hex: '#F88379' },
        { name: 'Silk Mint Green', hex: '#98FFB0' },
        { name: 'Silk Holly Green', hex: '#008000' },
        { name: 'Silk Sky Blue', hex: '#87CEEB' },
        { name: 'Silk Blue Green', hex: '#0D98BA' },
        { name: 'Silk Blue Purple', hex: '#6A5ACD' },
        { name: 'Silk Bluish Purple', hex: '#7B68EE' },
        { name: 'Silk Blue Magenta', hex: '#8B008B' },
        { name: 'Silk Black Red', hex: '#65516A' },
        { name: 'Silk Black Purple', hex: '#3D2B56' },
        { name: 'Silk Black Green', hex: '#2D5A27' },
        { name: 'Silk Green Red', hex: '#716C57' },
        { name: 'Silk Blue Green Orange', hex: '#2E8B57' },
        { name: 'Silk Blue Purple Black', hex: '#3B3178' },
        { name: 'Silk Yellow Purple', hex: '#9B59B6' },
      ],
    },
    {
      material: 'PLA Basic',
      colors: [
        { name: 'Black', hex: '#000000' },
        { name: 'White', hex: '#FFFFFF' },
        { name: 'Grey', hex: '#8F949B' },
        { name: 'Red', hex: '#EA140E' },
        { name: 'Yellow', hex: '#F6D701' },
        { name: 'Green', hex: '#228B22' },
        { name: 'Cyan', hex: '#00BFFF' },
        { name: 'Purple', hex: '#603BA0' },
        { name: 'Pink', hex: '#F9B0BD' },
        { name: 'Hot Pink', hex: '#FF69B4' },
        { name: 'Beige', hex: '#FEE7BF' },
        { name: 'Translucent', hex: '#E9E9E7' },
        { name: 'Sunflower Yellow', hex: '#FFDA03' },
        { name: 'Cobalt Blue', hex: '#0047AB' },
        { name: 'Apple Green', hex: '#8DB600' },
        { name: 'Turquoise Green', hex: '#00CED1' },
        { name: 'Cocoa Brown', hex: '#6B3A2A' },
        { name: 'Misty Blue', hex: '#7EB6D0' },
      ],
    },
    {
      material: 'PLA Galaxy',
      colors: [
        { name: 'Galaxy Purple', hex: '#3A2F6F' },
        { name: 'Galaxy Black', hex: '#1A1A2E' },
        { name: 'Galaxy Peacock Blue', hex: '#21606B' },
      ],
    },
    {
      material: 'PLA Sparkle',
      colors: [
        { name: 'Sparkle Black', hex: '#1A1A1A' },
        { name: 'Sparkle Gold', hex: '#DAA520' },
        { name: 'Sparkle Green', hex: '#2E8B57' },
        { name: 'Sparkle Red', hex: '#B22222' },
        { name: 'Sparkle Dark Grey', hex: '#4A4A4A' },
        { name: 'Sparkle Turquoise', hex: '#40E0D0' },
        { name: 'Sparkle Purplish Grey', hex: '#7A6B8A' },
      ],
    },
    {
      material: 'PLA Marble',
      colors: [
        { name: 'Marble', hex: '#E8E0D8' },
        { name: 'Marble Brick Red', hex: '#A04030' },
        { name: 'Marble Cement Grey', hex: '#B0AFA8' },
      ],
    },
    {
      material: 'PLA Glow',
      colors: [
        { name: 'Glow Blue', hex: '#00BFFF' },
        { name: 'Glow Green', hex: '#39FF14' },
        { name: 'Glow Yellow', hex: '#FFFF33' },
        { name: 'Glow Orange', hex: '#FF6600' },
        { name: 'Glow Pink', hex: '#FF69B4' },
      ],
    },
    {
      material: 'PETG Pro',
      colors: [
        { name: 'Black', hex: '#000000' },
        { name: 'White', hex: '#FFFFFF' },
        { name: 'Grey', hex: '#8F949B' },
        { name: 'Silver', hex: '#C0C0C0' },
        { name: 'Red', hex: '#EA140E' },
        { name: 'Yellow', hex: '#F6D701' },
        { name: 'Green', hex: '#228B22' },
        { name: 'Blue', hex: '#2240AF' },
        { name: 'Light Blue', hex: '#6CB4EE' },
        { name: 'Purple', hex: '#603BA0' },
        { name: 'Pink', hex: '#F9B0BD' },
        { name: 'Olive Green', hex: '#6B8E23' },
        { name: 'Burgundy Red', hex: '#800020' },
      ],
    },
    {
      material: 'Rapid PETG',
      colors: [
        { name: 'Black', hex: '#000000' },
        { name: 'White', hex: '#FFFFFF' },
        { name: 'Grey', hex: '#8F949B' },
        { name: 'Space Grey', hex: '#5D5D5D' },
        { name: 'Red', hex: '#EA140E' },
        { name: 'Orange', hex: '#FD7C18' },
        { name: 'Yellow', hex: '#F6D701' },
        { name: 'Green', hex: '#08E327' },
        { name: 'Blue', hex: '#2240AF' },
        { name: 'Brown', hex: '#9E6A4B' },
        { name: 'Beige', hex: '#FEE7BF' },
        { name: 'Transparent', hex: '#F3F3F3' },
      ],
    },
  ],
};

const OVERTURE: ManufacturerCatalog = {
  name: 'Overture',
  materials: [
    {
      material: 'PLA',
      colors: [
        { name: 'Black', hex: '#000000' },
        { name: 'Sparkle Black', hex: '#000000' },
        { name: 'Space Grey', hex: '#63646B' },
        { name: 'Cement Gray', hex: '#697272' },
        { name: 'Metallic Gray', hex: '#8B98AC' },
        { name: 'Royal Silver', hex: '#C6CDD2' },
        { name: 'Light Grey', hex: '#C7D4D6' },
        { name: 'White', hex: '#FFFEFA' },
        { name: 'Cold White', hex: '#FFFFFF' },
        { name: 'Wine', hex: '#BE133B' },
        { name: 'Fresh Red', hex: '#E31A1F' },
        { name: 'Red', hex: '#E9301E' },
        { name: 'Jeans Red', hex: '#FF706B' },
        { name: 'Pink', hex: '#F09BB5' },
        { name: 'Sakura Pink', hex: '#FFD1D1' },
        { name: 'Chocolate', hex: '#57361C' },
        { name: 'Brown', hex: '#D7A86A' },
        { name: 'Royal Copper', hex: '#A47456' },
        { name: 'Orange', hex: '#FF8E24' },
        { name: 'Yellow', hex: '#E6B535' },
        { name: 'Royal Gold', hex: '#FFCB47' },
        { name: 'Highlight Yellow', hex: '#E4FF33' },
        { name: 'Lemon Yellow', hex: '#FFED29' },
        { name: 'Light Yellow', hex: '#EFFF8A' },
        { name: 'Olive Green', hex: '#97A014' },
        { name: 'Green', hex: '#00C26B' },
        { name: 'Light Green', hex: '#8FFFA2' },
        { name: 'Glow In Dark (Green)', hex: '#EBF1E0' },
        { name: 'Morning Blue', hex: '#8FEEFF' },
        { name: 'Light Blue', hex: '#3ABBDE' },
        { name: 'Gray Blue', hex: '#81BAC1' },
        { name: 'Jeans Blue', hex: '#43729B' },
        { name: 'Blue', hex: '#033877' },
        { name: 'Purple', hex: '#6F4AB2' },
        { name: 'Sparkle Purple', hex: '#7701B2' },
      ],
    },
    {
      material: 'Matte PLA',
      colors: [
        { name: 'Carbon Fiber Black', hex: '#000000' },
        { name: 'Matte Black', hex: '#1D1E1E' },
        { name: 'Matte Light Grey', hex: '#BAC4C4' },
        { name: 'Matte Repose Gray', hex: '#B1A498' },
        { name: 'Matte White', hex: '#E6DEDE' },
        { name: 'Matte Brick Red', hex: '#D22D2F' },
        { name: 'Matte Red', hex: '#EB3B41' },
        { name: 'Matte Jeans Red', hex: '#F76E6E' },
        { name: 'Matte Pink', hex: '#FFE0E1' },
        { name: 'Matte Light Pink', hex: '#F7E6DE' },
        { name: 'Matte Baby Pink', hex: '#FFE0E0' },
        { name: 'Matte Chocolate', hex: '#503529' },
        { name: 'Matte Wood', hex: '#CAAC78' },
        { name: 'Matte Light Brown', hex: '#EDD5A6' },
        { name: 'Matte Light Blue', hex: '#99FFFA' },
        { name: 'Matte Blue', hex: '#005DA4' },
        { name: 'Matte Jeans Blue', hex: '#6787AD' },
        { name: 'Matte Dark Orange', hex: '#DC4116' },
        { name: 'Matte Orange', hex: '#F3C102' },
        { name: 'Matte Yellow', hex: '#EFDC4C' },
        { name: 'Matte Butter Yellow', hex: '#FCFAA6' },
        { name: 'Matte Light Orange', hex: '#F2B87B' },
        { name: 'Matte Skin', hex: '#F0DDC2' },
        { name: 'Matte Beige', hex: '#E7EFD7' },
        { name: 'Matte Olive Green', hex: '#A88704' },
        { name: 'Matte Grass Green', hex: '#CEFF5C' },
        { name: 'Matte Pale Green', hex: '#BECBA8' },
        { name: 'Matte Light Teal', hex: '#C7FFE3' },
        { name: 'Matte Light Green', hex: '#AFDEB9' },
        { name: 'Matte Bamboo Green', hex: '#A1D66B' },
        { name: 'Matte Turquoise', hex: '#60F0E7' },
        { name: 'Matte Green', hex: '#519F62' },
        { name: 'Matte Army Green', hex: '#6E8451' },
        { name: 'Matte Gray Green', hex: '#666F60' },
        { name: 'Matte Slate Gray', hex: '#4F6B86' },
        { name: 'Matte Navy Blue', hex: '#072E4E' },
        { name: 'Matte Lavender', hex: '#7E5777' },
        { name: 'Matte Purple', hex: '#8C69B5' },
        { name: 'Matte Lilac', hex: '#ECD1FF' },
        { name: 'Matte Black-White', hex: '#000000' },
        { name: 'Matte Orange-Red', hex: '#FCAB59' },
        { name: 'Matte Blue-Red', hex: '#0074BD' },
        { name: 'Light Blue-Yellow', hex: '#B8FFFF' },
      ],
    },
    {
      material: 'Rock PLA',
      colors: [
        { name: 'Rock White', hex: '#FFFFFF' },
        { name: 'Fossil Rock', hex: '#C2C0BA' },
        { name: 'Sedimentary Rock', hex: '#C4B199' },
        { name: 'Turquoise Green', hex: '#86DACD' },
        { name: 'Turquoise Blue', hex: '#A3EAFF' },
        { name: 'Mars Red', hex: '#D76D3B' },
        { name: 'Marigold Yellow', hex: '#FFDA47' },
        { name: 'Moonlight Gray', hex: '#E4E6E7' },
        { name: 'Mist Gray', hex: '#F2F3EC' },
        { name: 'Slate Gray', hex: '#638BA1' },
        { name: 'Haze Gray', hex: '#C3D2DA' },
        { name: 'Muted Gray', hex: '#CED2D4' },
      ],
    },
    {
      material: 'PLA Professional',
      colors: [
        { name: 'Black', hex: '#0D110E' },
        { name: 'Light Gray', hex: '#74777D' },
        { name: 'Space Grey', hex: '#969BA2' },
        { name: 'Silver Metal', hex: '#C9D0D4' },
        { name: 'White', hex: '#E8E4DF' },
        { name: 'Champagne', hex: '#F4F4EA' },
        { name: 'Wine', hex: '#800020' },
        { name: 'Fresh Red', hex: '#F00000' },
        { name: 'Red', hex: '#FF0505' },
        { name: 'Jeans Red', hex: '#CE4F4E' },
        { name: 'Pink', hex: '#F092B3' },
        { name: 'Sakura Pink', hex: '#FEC2C2' },
        { name: 'Chocolate', hex: '#50311E' },
        { name: 'Brown', hex: '#AB713E' },
        { name: 'Orange', hex: '#FF852E' },
        { name: 'Royal Gold', hex: '#E3B145' },
        { name: 'Yellow', hex: '#EEEA44' },
        { name: 'Light Yellow', hex: '#F4D563' },
        { name: 'Highlight Yellow', hex: '#EBFF57' },
        { name: 'Army Green', hex: '#8A8850' },
        { name: 'Green', hex: '#0CCF81' },
        { name: 'Light Green', hex: '#BCD69B' },
        { name: 'Olive Green', hex: '#B0BE50' },
        { name: 'Light Blue', hex: '#99F1FF' },
        { name: 'Gray Blue', hex: '#8FBBC1' },
        { name: 'Morning Blue', hex: '#75AFCD' },
        { name: 'Jeans Blue', hex: '#73A1BA' },
        { name: 'Digital Blue', hex: '#0099E6' },
        { name: 'Dark Blue', hex: '#003B80' },
        { name: 'Purple', hex: '#7659B5' },
        { name: 'Moonlight Silver', hex: '#D5DCDD' },
        { name: 'Bronze', hex: '#704515' },
        { name: 'Copper', hex: '#BB8330' },
      ],
    },
    {
      material: 'Super PLA+',
      colors: [
        { name: 'Black', hex: '#000000' },
        { name: 'Light Gray', hex: '#BAC8C9' },
        { name: 'White', hex: '#FFFFFF' },
        { name: 'Red', hex: '#E60000' },
        { name: 'Pink', hex: '#FF5786' },
        { name: 'Sakura Pink', hex: '#FFCCCD' },
        { name: 'Light Brown', hex: '#B8AF99' },
        { name: 'Orange', hex: '#FF7A33' },
        { name: 'Yellow', hex: '#FFD342' },
        { name: 'Green', hex: '#00D17A' },
        { name: 'Dark Blue', hex: '#183681' },
        { name: 'Purple', hex: '#8761C1' },
      ],
    },
    {
      material: 'Easy PLA',
      colors: [
        { name: 'Easy Black', hex: '#000000' },
        { name: 'Easy Cement Grey', hex: '#697272' },
        { name: 'Easy Space Gray', hex: '#B2B8B8' },
        { name: 'Easy Rock White', hex: '#EDF0F2' },
        { name: 'Easy White', hex: '#FFFFFF' },
        { name: 'Easy Red', hex: '#FF2C29' },
        { name: 'Easy Orange', hex: '#FF5F2E' },
        { name: 'Easy Caramel', hex: '#A88D5D' },
        { name: 'Easy Digital Blue', hex: '#0696EF' },
        { name: 'Easy Green', hex: '#4DFF64' },
        { name: 'Glow Red', hex: '#FF7D7A' },
        { name: 'Glow Orange', hex: '#FF9C66' },
        { name: 'Glow Yellow', hex: '#EBFF6B' },
        { name: 'Glow Blue', hex: '#5EB7D4' },
        { name: 'Shimmer Silver Green', hex: '#9ECB86' },
        { name: 'Shimmer Bronze', hex: '#81BA6D' },
        { name: 'Shimmer Dark Green', hex: '#008059' },
        { name: 'Shimmer Purple', hex: '#906482' },
        { name: 'Easy Pink', hex: '#FFC0CB' },
        { name: 'Easy Yellow', hex: '#FCFF66' },
        { name: 'Easy Pumpkin Orange', hex: '#FF8D5C' },
        { name: 'Easy Beige', hex: '#F7F6ED' },
        { name: 'Easy Yolk Yellow', hex: '#FFE357' },
        { name: 'Easy Sky Blue', hex: '#3BC9ED' },
        { name: 'Easy Cobalt Blue', hex: '#274DA0' },
        { name: 'Easy Purple', hex: '#7B49A2' },
        { name: 'Easy Pine Green', hex: '#00A5A8' },
        { name: 'Easy Magenta', hex: '#FD3DB5' },
      ],
    },
    {
      material: 'Silk PLA',
      colors: [
        { name: 'Silk Gray', hex: '#394658' },
        { name: 'Silk Silver', hex: '#818FA0' },
        { name: 'Silk White', hex: '#DDD4CA' },
        { name: 'Silk Rose Red', hex: '#9B0350' },
        { name: 'Silk Fresh Red', hex: '#CC0201' },
        { name: 'Silk Red', hex: '#DA445A' },
        { name: 'Silk Silver Pink', hex: '#A8726B' },
        { name: 'Silk Christmas Red', hex: '#CE5D4C' },
        { name: 'Silk Pink', hex: '#DF877C' },
        { name: 'Silk Copper', hex: '#641501' },
        { name: 'Silk Neon Green', hex: '#91C800' },
        { name: 'Silk Green', hex: '#018E63' },
        { name: 'Silk Purple', hex: '#7769BC' },
        { name: 'Silk Blue', hex: '#0353BA' },
        { name: 'Silk Orange', hex: '#F44703' },
        { name: 'Silk Yellow', hex: '#ECC403' },
        { name: 'Silk Gold', hex: '#F9E352' },
        { name: 'Silk Gold-Silver', hex: '#B2C2C7' },
        { name: 'Silk Green-Silver', hex: '#00C28E' },
        { name: 'Silk Blue-Silver', hex: '#009DE0' },
        { name: 'Silk Blue-Yellow', hex: '#FFFF5C' },
        { name: 'Silk Green-Blue', hex: '#005AAD' },
        { name: 'Silk Purple-Gold', hex: '#702AB2' },
        { name: 'Silk Green-Magenta', hex: '#9FFF05' },
        { name: 'Silk Magenta-Gold', hex: '#B71A7D' },
        { name: 'Silk Red-Gold', hex: '#F04C64' },
      ],
    },
    {
      material: 'Air PLA',
      colors: [
        { name: 'Air Black', hex: '#000000' },
        { name: 'Air Light Gray', hex: '#AFAEAB' },
        { name: 'Air White', hex: '#EDD5B7' },
        { name: 'Air Orange', hex: '#FD9106' },
        { name: 'Air Wood', hex: '#E6C49E' },
        { name: 'Air Yellow', hex: '#F5C001' },
        { name: 'Air Neon Green', hex: '#C0D904' },
      ],
    },
    {
      material: 'PETG',
      colors: [
        { name: 'Black', hex: '#000000' },
        { name: 'Space Grey', hex: '#76797D' },
        { name: 'Light Gray', hex: '#D5D8DD' },
        { name: 'Rock White', hex: '#FFFFFF' },
        { name: 'White', hex: '#F5F5F4' },
        { name: 'Transparent Red', hex: '#CE333E' },
        { name: 'Red', hex: '#FF0000' },
        { name: 'Magenta', hex: '#C80181' },
        { name: 'Pink', hex: '#F79DBC' },
        { name: 'Orange', hex: '#FF854D' },
        { name: 'Gold', hex: '#CE8D00' },
        { name: 'Brown', hex: '#A47C48' },
        { name: 'Yellow', hex: '#FFC946' },
        { name: 'Grass Green', hex: '#C4D802' },
        { name: 'Green', hex: '#38AF69' },
        { name: 'Transparent Green', hex: '#019A45' },
        { name: 'Army Green', hex: '#404720' },
        { name: 'Digital Blue', hex: '#0378D0' },
        { name: 'Blue', hex: '#034E89' },
        { name: 'Transparent Blue', hex: '#09048E' },
        { name: 'Starry Blue', hex: '#142B4B' },
        { name: 'Sparkle Blue', hex: '#253F56' },
        { name: 'Purple', hex: '#7142A3' },
      ],
    },
    {
      material: 'TPU',
      colors: [
        { name: 'Black', hex: '#000000' },
        { name: 'Space Grey', hex: '#90999D' },
        { name: 'Grey', hex: '#E2E7E9' },
        { name: 'White', hex: '#FFFFFF' },
        { name: 'Red', hex: '#D7021C' },
        { name: 'Bright Pink', hex: '#FFBDD1' },
        { name: 'Orange', hex: '#FFA11D' },
        { name: 'Brown', hex: '#A47C48' },
        { name: 'Yellow', hex: '#FFDF03' },
        { name: 'Green', hex: '#00EB75' },
        { name: 'Digital Blue', hex: '#0378D0' },
        { name: 'Blue', hex: '#274E96' },
        { name: 'Purple', hex: '#8B69CE' },
        { name: 'Neon Green', hex: '#2EFF6D' },
        { name: 'Neon Orange', hex: '#FA8E36' },
        { name: 'Neon Red', hex: '#FF3F38' },
        { name: 'Light Green', hex: '#A0FD62' },
      ],
    },
    {
      material: 'High Speed TPU',
      colors: [
        { name: 'Black', hex: '#000000' },
        { name: 'Gray', hex: '#CDCFD5' },
        { name: 'White', hex: '#FFFFFF' },
        { name: 'Pink', hex: '#FFA3C6' },
        { name: 'Translucent Red', hex: '#C00000' },
        { name: 'Translucent Blue', hex: '#386DFF' },
        { name: 'Translucent Orange', hex: '#FA4616' },
        { name: 'Translucent Purple', hex: '#8014C8' },
        { name: 'Translucent Green', hex: '#00E691' },
        { name: 'Orange', hex: '#FF8B47' },
        { name: 'Grass Green', hex: '#B1FF0A' },
        { name: 'Neon Magenta', hex: '#FB23AF' },
        { name: 'Neon Yellow', hex: '#FEF71D' },
        { name: 'Pastel Rose', hex: '#F5D0B7' },
        { name: 'Luminous Pink', hex: '#DCDCE4' },
        { name: 'Luminous Electric Indigo', hex: '#C3D3E0' },
        { name: 'Luminous Blue', hex: '#E9E7E7' },
        { name: 'Luminous Orange', hex: '#E8E8E8' },
        { name: 'Luminous Green', hex: '#ECF2E9' },
      ],
    },
    {
      material: 'ABS',
      colors: [
        { name: 'Black', hex: '#000000' },
        { name: 'Ash Grey', hex: '#6C7074' },
        { name: 'Diamond Gray', hex: '#8C8C8C' },
        { name: 'Slate Gray', hex: '#91A0B6' },
        { name: 'Gray', hex: '#CACAC9' },
        { name: 'Natural', hex: '#F8F8EE' },
        { name: 'White', hex: '#FFFFFF' },
        { name: 'Dark Red', hex: '#FF311F' },
        { name: 'Pink', hex: '#F79DBC' },
        { name: 'Orange', hex: '#FF6229' },
        { name: 'Diamond Orange', hex: '#FF8133' },
        { name: 'Royal Gold', hex: '#F0A400' },
        { name: 'Gold', hex: '#FFDA05' },
        { name: 'Yellow', hex: '#FFFF47' },
        { name: 'Grass Green', hex: '#C4D802' },
        { name: 'Green', hex: '#3D9441' },
        { name: 'Glow Green', hex: '#EBEFEE' },
        { name: 'Dark Green', hex: '#008F77' },
        { name: 'Light Blue', hex: '#5DC5EA' },
        { name: 'Blue', hex: '#00628F' },
        { name: 'Dark Blue', hex: '#034E89' },
        { name: 'Purple', hex: '#7142A3' },
        { name: 'Diamond Purple', hex: '#A04ED0' },
      ],
    },
    {
      material: 'ASA',
      colors: [
        { name: 'Black', hex: '#000000' },
        { name: 'Gray', hex: '#B5B9BA' },
        { name: 'White', hex: '#FFFFFF' },
        { name: 'Red', hex: '#AF251E' },
        { name: 'Diamond Red', hex: '#C01616' },
        { name: 'Brown', hex: '#785F53' },
        { name: 'Orange', hex: '#FF9A40' },
        { name: 'Yellow', hex: '#FFE802' },
        { name: 'Natural', hex: '#F1E6B3' },
        { name: 'Olive Green', hex: '#6B7550' },
        { name: 'Diamond Green', hex: '#26A648' },
        { name: 'Green', hex: '#01AA5E' },
        { name: 'Diamond Blue', hex: '#324485' },
        { name: 'Blue', hex: '#002979' },
        { name: 'Purple', hex: '#7959B6' },
      ],
    },
    {
      material: 'Easy Nylon',
      colors: [
        { name: 'Black', hex: '#000000' },
        { name: 'Gray', hex: '#808E93' },
      ],
    },
    {
      material: 'PC Professional',
      colors: [
        { name: 'Black', hex: '#000000' },
        { name: 'Gray', hex: '#E3E8E7' },
        { name: 'White', hex: '#FFFFFF' },
        { name: 'Red', hex: '#D7021C' },
        { name: 'Blue', hex: '#0378D0' },
      ],
    },
  ],
};

export const MANUFACTURER_CATALOGS: ManufacturerCatalog[] = [ELEGOO, OVERTURE];

export function getManufacturerNames(): string[] {
  return MANUFACTURER_CATALOGS.map((m) => m.name);
}

export function getMaterialsForManufacturer(manufacturer: string): string[] {
  const catalog = MANUFACTURER_CATALOGS.find((m) => m.name === manufacturer);
  return catalog ? catalog.materials.map((m) => m.material) : [];
}

export function getColorsForMaterial(manufacturer: string, material: string): ManufacturerColor[] {
  const catalog = MANUFACTURER_CATALOGS.find((m) => m.name === manufacturer);
  if (!catalog) return [];
  const mat = catalog.materials.find((m) => m.material === material);
  return mat ? mat.colors : [];
}
